//Para dois arrays do mesmo tamanho, pegar cada posicao e imprimir o menor numero.


const arrayA = [5, 10, 15, 20]
const arrayB = [10, 20, 30, 40]


if (arrayA[0] < arrayB[0]) {
    console.log(arrayA[0]);
}

else if (arrayB[0] < arrayA[0]) {
    console.log(arrayB[0]);
}
if (arrayA[1] < arrayB[1]) {
    console.log(arrayA[1]);
}

else if (arrayB[1] < arrayA[1]) {
    console.log(arrayB[1]);
}
if (arrayA[2] < arrayB[2]) {
    console.log(arrayA[2]);
}

else if (arrayB[2] < arrayA[2]) {
    console.log(arrayB[2]);
}
if (arrayA[3] < arrayB[3]) {
    console.log(arrayA[3]);
}

else if (arrayB[3] < arrayA[3]) {
    console.log(arrayB[3]);
}
if (arrayA[4] < arrayB[4]) {
    console.log(arrayA[4]);
}

else if (arrayB[4] < arrayA[4]) {
    console.log(arrayB[4]);
}